### ISSUE TITLE
Inertia js

### ISSUE THREAD

**Issue by vadimsg** [coderello/laravel-dynamic-rendering#1]
Hi, interesting project. Will it work smoothly with Inertia JS https://inertiajs.com?

**Comment by hivokas** [comment]
Hello @vadimsg! Thanks for your interest!
Yes, it will work smoothly with Inertia.js.
https://coderello.com is built using Inertia.js and also uses this package.

**Comment by vadimsg** [comment]
Fantastic, thanks!
