### ISSUE TITLE
ENOENT: no such file or directory, stat '/node_modules/rendertron/src/index.html'

### ISSUE THREAD

**Issue by shahabgohar** [coderello/laravel-dynamic-rendering#4]
Hi ! 
good effort . really liked your project.
I am also using inertia.
I followed all the steps mentioned in your documentation.
Now when i go to
localhost:3000
on which it is running
 i find this error

`
ENOENT: no such file or directory, stat '/home/shahab/web projects/inertia/Fitness/node_modules/rendertron/src/index.html'
`
and even i visit the route '/dashboard' i get this 
`
not found
`
Appreciate your help and response 
Thank You !

**Comment by hivokas** [comment]
Try to use `prerender` instead.
